---
- hosts: all
  become: yes
  tasks:

   - name: install webserver on ubuntu ansible nodes
     apt:
      name: git
      state: present
    
   - name: install tree
     service:
      name: tree
      state: started
  




